# Generated by Django 4.2.2 on 2023-06-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jurisprudencias",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("tipo_causa", models.CharField(max_length=20)),
                ("rol", models.CharField(max_length=50)),
                ("caratula", models.TextField()),
                ("nombre_proyecto", models.TextField()),
                ("fecha_sentencia", models.DateField(blank=True, null=True)),
                ("descriptores", models.TextField(blank=True, null=True)),
                ("link_sentencia", models.CharField(max_length=250)),
                ("url_sentencia", models.URLField(max_length=250)),
                ("activo", models.BooleanField(default=True)),
                ("tribunal", models.CharField(max_length=10)),
                ("tipo", models.CharField(max_length=10)),
                ("relacionada", models.CharField(default="", max_length=120)),
                ("visitas", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Valores",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("id_parametro", models.IntegerField()),
                ("id_item_lista", models.IntegerField(blank=True, null=True)),
                ("valor", models.TextField(blank=True, null=True)),
                ("parametro", models.CharField(max_length=120)),
                ("item", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "jurisprudencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tarea1.jurisprudencias",
                    ),
                ),
            ],
        ),
    ]
