# Generated by Django 4.2.2 on 2023-06-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarea1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisprudencias",
            name="id_jurisprudencia",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="valores",
            name="id_valores",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="jurisprudencias",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="valores",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
