# Generated by Django 4.2.2 on 2023-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tarea1",
            "0002_jurisprudencias_id_jurisprudencia_valores_id_valores_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valores",
            name="jurisprudencia",
        ),
        migrations.AddField(
            model_name="valores",
            name="id_jurisprudencia",
            field=models.IntegerField(default=1),
        ),
    ]
